<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24885" started-at="2020-06-18T18:24:12 IST" finished-at="2020-06-18T18:24:36 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24885" started-at="2020-06-18T18:24:12 IST" finished-at="2020-06-18T18:24:36 IST">
      <class name="reports.Ktc_TripsPage">
        <test-method status="PASS" signature="initialize()[pri:0, instance:reports.Ktc_TripsPage@522a32b1]" name="initialize" is-config="true" duration-ms="6747" started-at="2020-06-18T18:24:12 IST" finished-at="2020-06-18T18:24:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="login()[pri:0, instance:reports.Ktc_TripsPage@522a32b1]" name="login" is-config="true" duration-ms="16985" started-at="2020-06-18T18:24:18 IST" finished-at="2020-06-18T18:24:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="clk_Ktc_Reports()[pri:0, instance:reports.Ktc_TripsPage@522a32b1]" name="clk_Ktc_Reports" duration-ms="409" started-at="2020-06-18T18:24:35 IST" finished-at="2020-06-18T18:24:36 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at reports.Ktc_TripsPage.clk_Ktc_Reports(Ktc_TripsPage.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clk_Ktc_Reports -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:reports.Ktc_TripsPage@522a32b1]" name="teardown" is-config="true" duration-ms="698" started-at="2020-06-18T18:24:36 IST" finished-at="2020-06-18T18:24:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- reports.Ktc_TripsPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
